---
- name: ansible-provisioning
  hosts: localhost
  connection: local
  gather-facts: false  
  vars:
    aws_region: ap-northeast-2
    vpc_name: ansible-vpc
    vpc_cidr_block: 10.210.0.0/16
    subnet_cidr_block: 10.210.1.0/24
    instance_image: ami-06098fd00463352b6
    ec2_key_name: jypark_devos
    instance_type: t2.micro
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc_cidr_block}}"
      region: "{{aws_region}}"
      tags:
        Name: "{{vpc_name}}"
      tenancy: default
    register: result_vpc
  
  - name: Create subnet
  ec2_vpc_subnet:
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ result_vpc.vpc.id }}"
    cidr: "{{ subnet_cidr_block }}"
    tags:
      Name: Webserver Subnet
  register: result_subnet